[shell]
program = "/bin/bash"
args = ["-c", "cd /home/tom/Programming && tmux attach -t default || tmux new -s default"]

[env]
TERM = "xterm-256color"
EDITOR =  "neovim"

[colors]
[colors.primary]
# Blue transparent background
background = "0x21353c"
foreground = "0xf8f8f2"

[window]
opacity = 0.85
padding = { x = 1, y = 1 }
startup_mode = "Windowed"
decorations = "None"
dynamic_title = false

[font]
size = 11.5
[font.normal]
family = "Hack Nerd Font"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

